channels:
- conda-forge
dependencies:
- ase =3.23.0
- coveralls
- coverage
- codacy-coverage
- matplotlib =3.8.4
- numpy =1.26.4
- pyiron_base =0.9.12
- pyiron_atomistics =0.6.9
- pyiron-data =0.0.25
- pyiron_contrib >0.1.18
- pyiron_snippets >=0.1.1,<=0.1.3
- pyparsing =3.1.1
- scipy =1.14.0
- dill >=0.3
- seaborn >=0.13.0
- runnerase =0.3.3
- pyxtal >=0.6.0,<0.7
- python >= 3.10
- lammps
- nglview >=3.0.8
