channels:
- conda-forge
dependencies:
- ase =3.22.1
- coveralls
- coverage
- codacy-coverage
- matplotlib =3.8.2
- numpy =1.26.2
- pyiron_base =0.7.9
- pyiron_atomistics =0.3.7
- pyiron-data =0.0.25
- pyparsing =3.1.1
- scipy =1.11.4
- python >= 3.10
- lammps
- nglview >=3.0.8
- pip:
  - runnerase==0.3.3
