channels:
- conda-forge
dependencies:
- ipykernel
- myst-parser
- nbsphinx
- sphinx-gallery
- sphinx-rtd-theme
- ase =3.22.1
- coveralls
- coverage
- codacy-coverage
- matplotlib =3.8.3
- numpy =1.26.4
- pyiron_base =0.8.0
- pyiron_atomistics =0.4.16
- pyiron-data =0.0.25
- pyparsing =3.1.1
- scipy =1.11.4
- pip:
  - runnerase==0.3.3
