channels:
- conda-forge
dependencies:
- ipykernel
- nbsphinx
- ase =3.22.1
- coveralls
- coverage
- codacy-coverage
- matplotlib =3.8.2
- numpy =1.26.2
- pyiron_base =0.6.15
- pyiron_atomistics =0.3.7
- pyiron-data =0.0.25
- pyparsing =3.1.1
- scipy =1.11.4
