channels:
- conda-forge
dependencies:
- ipykernel
- nbsphinx
- ase =3.22.1
- coveralls
- coverage
- codacy-coverage
- matplotlib =3.8.2
- numpy =1.26.3
- pyiron_base =0.6.20
- pyiron_atomistics =0.4.4
- pyiron-data =0.0.25
- pyparsing =3.1.1
- scipy =1.11.4
