channels:
- conda-forge
dependencies:
- ipykernel
- myst-parser
- nbsphinx
- sphinx-gallery
- sphinx-rtd-theme
- ase =3.22.1
- coveralls
- coverage
- codacy-coverage
- matplotlib =3.8.4
- numpy =1.26.4
- pyiron_base =0.8.2
- pyiron_atomistics =0.5.2
- pyiron-data =0.0.25
- pyparsing =3.1.1
- scipy =1.13.0
- dill =0.3.8
- seaborn =0.13.2
- runnerase =0.3.3
