# This runs jobs which pyiron modules should run on pushes or PRs to main

name: Push-main-Pull-all

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pyiron:
    uses: pyiron/actions/.github/workflows/push-pull.yml@v3.3.3
    secrets: inherit
    with:
      notebooks-env-files: .ci_support/environment.yml .ci_support/environment-notebooks.yml
      python-version-alt2: exclude
      python-version-alt3: exclude
